ROLE_DOCUMENTS = {
    "admin": [
        "Company policies and procedures including employee conduct guidelines, disciplinary actions, and workplace safety protocols.",
        "Employee handbook and HR guidelines covering recruitment processes, performance evaluations, benefits administration, and termination procedures.",
        "Financial reports and budget information detailing quarterly earnings, expense analysis, cash flow statements, and investment portfolios.",
        "System administration documentation including server management, security protocols, backup procedures, and disaster recovery plans.",
        "Legal compliance requirements encompassing data privacy regulations, industry standards, audit procedures, and regulatory reporting obligations.",
        "Executive decision-making frameworks and strategic planning methodologies for organizational growth and market expansion.",
        "Risk management policies covering operational risks, cybersecurity threats, financial exposures, and business continuity planning.",
        "Vendor management and procurement guidelines including contract negotiations, supplier evaluations, and cost optimization strategies.",
        "Corporate governance standards and board meeting protocols for maintaining transparency and accountability.",
        "Facility management procedures covering office space planning, equipment maintenance, health and safety inspections, and environmental compliance.",
        "Data protection and privacy policies ensuring GDPR, CCPA, and HIPAA compliance across all organizational data handling processes.",
        "Emergency response procedures including evacuation plans, crisis communication protocols, and incident command structures.",
        "Intellectual property management covering patent applications, trademark registrations, copyright protections, and trade secret safeguards.",
        "Audit and compliance documentation including internal audit schedules, external auditor communications, and regulatory inspection protocols.",
        "Board of directors meeting minutes, resolutions, voting records, and strategic oversight committee recommendations.",
        "Executive compensation structures including salary bands, bonus calculations, stock option plans, and benefits packages.",
        "Organizational restructuring guidelines covering department mergers, role consolidations, and workforce optimization strategies.",
        "Insurance policies and claims management including liability coverage, property protection, workers compensation, and cyber insurance.",
        "Stakeholder communication strategies for investor relations, public announcements, media interactions, and regulatory disclosures.",
        "International business operations including foreign subsidiary management, cross-border compliance, and global taxation strategies.",
        "Merger and acquisition procedures covering due diligence processes, valuation methodologies, and integration planning frameworks.",
        "Corporate social responsibility initiatives including sustainability programs, community engagement, and ethical business practices.",
        "Information security governance including access control policies, data classification schemes, and cybersecurity incident response.",
        "Regulatory reporting requirements for SEC filings, tax submissions, environmental reports, and industry-specific disclosures.",
        "Strategic partnership agreements including joint ventures, licensing deals, distribution partnerships, and technology collaborations.",
        "Capital allocation frameworks covering investment decisions, funding priorities, dividend policies, and debt management strategies.",
        "Performance measurement systems including balanced scorecards, key performance indicators, and organizational effectiveness metrics.",
        "Change management policies for organizational transformation, technology adoption, and cultural evolution initiatives.",
        "Crisis management protocols including business continuity plans, communication strategies, and recovery procedures.",
        "Environmental, social, and governance (ESG) reporting standards and sustainability metrics tracking organizational impact."
    ],
    "manager": [
        "Team performance metrics including individual KPIs, productivity measurements, goal tracking systems, and performance improvement plans.",
        "Project management guidelines covering agile methodologies, resource allocation, timeline management, and stakeholder communication strategies.",
        "Meeting minutes and action items from weekly team standups, monthly reviews, quarterly planning sessions, and annual strategy meetings.",
        "Resource allocation strategies for optimizing team workload, skill development programs, and cross-functional collaboration initiatives.",
        "Team building activities and employee engagement programs designed to improve morale, communication, and collaborative effectiveness.",
        "Leadership development frameworks including coaching techniques, delegation strategies, and conflict resolution methodologies.",
        "Budget management and cost control procedures for department expenses, project budgets, and resource optimization initiatives.",
        "Performance review processes and employee development planning including career progression paths and skill enhancement programs.",
        "Communication protocols for inter-departmental coordination, client interactions, and escalation procedures for critical issues.",
        "Quality assurance standards and process improvement methodologies to ensure consistent delivery and continuous optimization.",
        "Change management strategies for implementing new processes, technologies, and organizational restructuring initiatives.",
        "Customer relationship management practices including client feedback analysis, service level agreements, and customer satisfaction metrics.",
        "Employee onboarding and training programs including orientation schedules, skill assessments, and mentorship assignment protocols.",
        "Workforce planning and capacity management including hiring forecasts, skill gap analysis, and succession planning strategies.",
        "Remote work policies and virtual team management guidelines for distributed workforce coordination and productivity monitoring.",
        "Conflict resolution procedures including mediation techniques, grievance handling processes, and disciplinary action protocols.",
        "Innovation management frameworks for idea generation, evaluation processes, and implementation of creative solutions.",
        "Vendor and supplier relationship management including service level agreements, performance monitoring, and contract negotiations.",
        "Risk assessment and mitigation strategies for project risks, operational challenges, and team-related issues.",
        "Time management and productivity optimization techniques including workflow analysis, task prioritization, and efficiency improvements.",
        "Employee recognition and reward systems including achievement celebrations, incentive programs, and career advancement opportunities.",
        "Cross-functional collaboration guidelines for matrix organization management and inter-departmental project coordination.",
        "Data-driven decision making processes including analytics interpretation, reporting standards, and performance dashboard utilization.",
        "Stakeholder management strategies for internal customers, external partners, and senior leadership engagement.",
        "Diversity and inclusion initiatives including unconscious bias training, equitable hiring practices, and inclusive leadership development.",
        "Process documentation and standardization procedures for operational consistency and knowledge transfer protocols.",
        "Crisis leadership and emergency management including team communication during disruptions and business continuity planning.",
        "Technology adoption and digital transformation management including tool evaluation, implementation planning, and change resistance handling.",
        "Customer service excellence standards including service delivery metrics, complaint resolution procedures, and client satisfaction improvement.",
        "Organizational culture development including values reinforcement, behavioral expectations, and cultural transformation initiatives."
    ],
    "developer": [
        "API documentation and endpoints including REST and GraphQL specifications, authentication methods, rate limiting, and error handling procedures.",
        "Code review guidelines covering coding standards, security best practices, performance optimization, and documentation requirements.",
        "Deployment procedures including CI/CD pipelines, environment configurations, rollback strategies, and production monitoring protocols.",
        "Technical architecture documents detailing system design patterns, microservices architecture, database schemas, and integration frameworks.",
        "Database schema and queries including optimization techniques, indexing strategies, backup procedures, and data migration protocols.",
        "Software development lifecycle methodologies including agile practices, version control workflows, and testing frameworks.",
        "Security implementation guidelines covering authentication systems, data encryption, vulnerability assessments, and penetration testing procedures.",
        "Performance monitoring and optimization techniques including application profiling, load testing, caching strategies, and scalability planning.",
        "Development environment setup and configuration including IDE settings, dependency management, and local testing procedures.",
        "Documentation standards for code comments, API specifications, user guides, and technical troubleshooting resources.",
        "Quality assurance and testing procedures including unit testing, integration testing, automated testing suites, and bug tracking workflows.",
        "DevOps practices and infrastructure management including containerization, orchestration, monitoring tools, and incident response procedures.",
        "Third-party integration guidelines including API consumption, webhook implementations, service mesh configurations, and vendor evaluation criteria.",
        "Mobile development standards covering cross-platform compatibility, responsive design principles, and app store deployment procedures.",
        "Cloud computing best practices including AWS, Azure, and GCP service utilization, cost optimization, and multi-cloud strategies.",
        "Microservices architecture patterns including service decomposition, inter-service communication, distributed tracing, and fault tolerance mechanisms.",
        "Data engineering pipelines covering ETL processes, real-time streaming, data warehousing, and analytics infrastructure management.",
        "Frontend development frameworks including React, Angular, Vue.js implementations, component libraries, and state management solutions.",
        "Backend development standards covering server-side frameworks, middleware implementation, session management, and API gateway configurations.",
        "Machine learning and AI integration guidelines including model deployment, MLOps practices, data preprocessing, and inference optimization.",
        "Blockchain and distributed ledger technologies including smart contract development, consensus mechanisms, and decentralized application architecture.",
        "Cybersecurity implementation including OWASP compliance, secure coding practices, threat modeling, and security testing methodologies.",
        "Performance engineering including load balancing, caching strategies, database optimization, and application performance monitoring solutions.",
        "Legacy system modernization including refactoring strategies, migration planning, compatibility maintenance, and technical debt management.",
        "Open source contribution guidelines including license compliance, community engagement, project maintenance, and code contribution standards.",
        "Disaster recovery and backup strategies including data replication, failover procedures, recovery time objectives, and business continuity planning.",
        "Monitoring and observability including logging standards, metrics collection, alerting systems, and distributed system debugging techniques.",
        "Container orchestration using Kubernetes including pod management, service discovery, ingress controllers, and cluster administration.",
        "Automated testing frameworks including test-driven development, behavior-driven development, continuous testing, and quality gate implementations.",
        "Software architecture patterns including event-driven architecture, CQRS, domain-driven design, and hexagonal architecture implementations."
    ]
}